<?php

/*
|--------------------------------------------------------------------------
| PDF Service Test Script
|--------------------------------------------------------------------------
|
| This script tests the PDF generation service to verify it's working correctly.
| Run this from the command line: php test-pdf-service.php
|
*/

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

echo "===========================================\n";
echo "PDF Service Test\n";
echo "===========================================\n\n";

// Check current configuration
$service = config('pdf.service');
echo "Current PDF Service: " . $service . "\n\n";

if ($service === 'pdfshift') {
    $apiKey = config('pdf.pdfshift.api_key');
    if (empty($apiKey)) {
        echo "❌ ERROR: PDFShift API key not configured!\n";
        echo "   Please add PDFSHIFT_API_KEY to your .env file\n\n";
        exit(1);
    }
    echo "✅ PDFShift API key is configured\n";
    echo "   API Key: " . substr($apiKey, 0, 10) . "...\n\n";
}

// Test HTML
$testHtml = '
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #333; }
        .box { border: 2px solid #000; padding: 15px; margin: 10px 0; }
    </style>
</head>
<body>
    <h1>PDF Service Test</h1>
    <div class="box">
        <p>This is a test PDF generated by the PdfService class.</p>
        <p>Service: ' . $service . '</p>
        <p>Generated at: ' . date('Y-m-d H:i:s') . '</p>
    </div>
</body>
</html>
';

echo "Generating test PDF...\n";

try {
    $pdfBinary = \App\Services\PdfService::generateFromHtml($testHtml);

    $outputFile = __DIR__ . '/test-output.pdf';
    file_put_contents($outputFile, $pdfBinary);

    echo "✅ SUCCESS! PDF generated successfully\n";
    echo "   Output file: " . $outputFile . "\n";
    echo "   File size: " . number_format(strlen($pdfBinary)) . " bytes\n\n";

    echo "Please open test-output.pdf to verify the PDF looks correct.\n";

} catch (Exception $e) {
    echo "❌ ERROR: " . $e->getMessage() . "\n";
    echo "\nCheck storage/logs/laravel.log for more details.\n";
    exit(1);
}

echo "\n===========================================\n";
echo "Test Complete\n";
echo "===========================================\n";
