<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BusinessApplication extends Model
{
    use HasFactory;

    protected $fillable = [
        'application_type',
        'contact_person_name',
        'physical_address',
        'physical_postcode',
        'billing_address',
        'billing_postcode',
        'client_licence',
        'client_dob',
        'client_email',
        'client_mobile',
        'postcode_phy',
        'postcode_bill',
        'drivers_licence',
        'dob',
        'email',
        'mobile',
        'legal_name',
        'trading_name',
        'gst_no',
        'company_number',
        'nzbn_number',
        'company_no',
        'nzbn',
        'nature_business',
        'date_incorp',
        'paid_capital',
        'monthly_purchases',
        'credit_limit',
        'directors',
        'dir1_name',
        'dir1_mobile',
        'dir1_dl',
        'dir1_address',
        'dir1_pc',
        'dir2_name',
        'dir2_mobile',
        'dir2_dl',
        'dir2_address',
        'dir2_pc',
        'po_required',
        'accounts_email_opt',
        'accounts_email',
        'accounts_contact',
        'accounts_mobile',
        'bank_branch',
        'bank_account_no',
        'ref1_name',
        'ref1_company',
        'ref1_contact',
        'ref2_name',
        'ref2_company',
        'ref2_contact',
        'ref3_name',
        'ref3_company',
        'ref3_contact',
        'g1_name',
        'g1_address',
        'g1_dob',
        'g1_witness_name',
        'g1_witness_occ',
        'g1_witness_addr',
        'g2_name',
        'g2_address',
        'g2_dob',
        'g2_witness_name',
        'g2_witness_occ',
        'g2_witness_addr',
        'terms_agreed',
        'accept_terms',
        'account_name',
        'amount',
    ];
}